services:
  # Backend - API de Node.js
  - type: web
    name: tienda-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
    
  # Frontend - React/Vite  
  - type: static
    name: tienda-frontend
    buildCommand: npm install && npm run build
    publishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://tienda-backend.onrender.com/api